//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace EAI.Service.Transaction.F0101_Rs {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
        
        /// <remarks/>
        public string DebugLevel;
        
        /// <remarks/>
        public string ErrCode;
        
        /// <remarks/>
        public string RecSize;
        
        /// <remarks/>
        public string TimeOut;
        
        /// <remarks/>
        public string Capacity;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public ulong PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRs MsgRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRs {
        
        /// <remarks/>
        public IFXEAIBodyMsgRsHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRsSvcRs SvcRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsHeader {
        
        /// <remarks/>
        public string TxnId;
        
        /// <remarks/>
        public string RspCode;
        
        /// <remarks/>
        public string Desc;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsSvcRs {
        
        /// <remarks/>
        public string CUSRNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string CNAME;
        
        /// <remarks/>
        public string ZIPCD1;
        
        /// <remarks/>
        public string ADDR1;
        
        /// <remarks/>
        public string ZIPCD2;
        
        /// <remarks/>
        public string ADDR2;
        
        /// <remarks/>
        public string AREA1;
        
        /// <remarks/>
        public string TELNO1;
        
        /// <remarks/>
        public string EXT1;
        
        /// <remarks/>
        public string AREA2;
        
        /// <remarks/>
        public string TELNO2;
        
        /// <remarks/>
        public string EXT2;
        
        /// <remarks/>
        public string MPHONE;
        
        /// <remarks/>
        public string FAXAREA;
        
        /// <remarks/>
        public string FAXNO;
        
        /// <remarks/>
        public string FAXFG;
        
        /// <remarks/>
        public string EMAIL;
        
        /// <remarks/>
        public string EMAILFG;
        
        /// <remarks/>
        public string KINDCD;
        
        /// <remarks/>
        public string QID;
        
        /// <remarks/>
        public string BCODE;
        
        /// <remarks/>
        public string JOBCD;
        
        /// <remarks/>
        public string TAXCD;
        
        /// <remarks/>
        public string BIRTHDAY;
        
        /// <remarks/>
        public string INCOMEFG;
        
        /// <remarks/>
        public string CMPSCOP;
        
        /// <remarks/>
        public string NET;
        
        /// <remarks/>
        public string BUILD;
        
        /// <remarks/>
        public string RIGHT;
        
        /// <remarks/>
        public string CAPITAL;
        
        /// <remarks/>
        public string STAFF;
        
        /// <remarks/>
        public string CNTRY;
        
        /// <remarks/>
        public string RISKCRY;
        
        /// <remarks/>
        public string CITY;
        
        /// <remarks/>
        public string SEX;
        
        /// <remarks/>
        public string EDU;
        
        /// <remarks/>
        public string MARIFG;
        
        /// <remarks/>
        public string PCIFKEY;
        
        /// <remarks/>
        public string PCIFERR;
        
        /// <remarks/>
        public string PIDNAM;
        
        /// <remarks/>
        public string PIDBIR;
        
        /// <remarks/>
        public string DISPFG;
        
        /// <remarks/>
        public string DEADFG;
        
        /// <remarks/>
        public string STOPFG;
        
        /// <remarks/>
        public string WTHDFG;
        
        /// <remarks/>
        public string OPENFG;
        
        /// <remarks/>
        public string REFUSE;
        
        /// <remarks/>
        public string GATEFG;
        
        /// <remarks/>
        public string INTRFG;
        
        /// <remarks/>
        public string MAILFG;
        
        /// <remarks/>
        public string TAXFG;
        
        /// <remarks/>
        public string PASSNO;
        
        /// <remarks/>
        public string PASSEND;
        
        /// <remarks/>
        public string PASSOPN;
        
        /// <remarks/>
        public string INQPW1;
        
        /// <remarks/>
        public string FAXPW1;
        
        /// <remarks/>
        public string TRNPW1;
        
        /// <remarks/>
        public string INQPW2;
        
        /// <remarks/>
        public string FAXPW2;
        
        /// <remarks/>
        public string TRNPW2;
        
        /// <remarks/>
        public string CODE;
        
        /// <remarks/>
        public string EMPNO;
        
        /// <remarks/>
        public string LAWFG;
        
        /// <remarks/>
        public string LAWDAY;
        
        /// <remarks/>
        public string REMARK;
        
        /// <remarks/>
        public string CONTACT;
        
        /// <remarks/>
        public string CONREL;
        
        /// <remarks/>
        public string CONTEL1;
        
        /// <remarks/>
        public string CONTEL2;
        
        /// <remarks/>
        public string DPFIRDY;
        
        /// <remarks/>
        public string LOANFIR;
        
        /// <remarks/>
        public string OCIFKEY;
        
        /// <remarks/>
        public string OCIFERR;
        
        /// <remarks/>
        public string CHGDAY;
        
        /// <remarks/>
        public string CREBRN;
        
        /// <remarks/>
        public string KEMPNO;
        
        /// <remarks/>
        public string LTXDAY;
        
        /// <remarks/>
        public string LBRNO;
        
        /// <remarks/>
        public string ENAM1;
        
        /// <remarks/>
        public string ENAM2;
        
        /// <remarks/>
        public string EADDR1;
        
        /// <remarks/>
        public string EADDR2;
        
        /// <remarks/>
        public string EADDR3;
        
        /// <remarks/>
        public string EADDR4;
        
        /// <remarks/>
        public string EFAXAREA;
        
        /// <remarks/>
        public string EFAXNO;
        
        /// <remarks/>
        public string EFAXFG;
        
        /// <remarks/>
        public string ADVEMAIL;
        
        /// <remarks/>
        public string ADVEMLFG;
        
        /// <remarks/>
        public string ADVFEFG;
        
        /// <remarks/>
        public string ADVFG;
        
        /// <remarks/>
        public string ADVMAIL;
        
        /// <remarks/>
        public string ADVADR1;
        
        /// <remarks/>
        public string ADVADR2;
        
        /// <remarks/>
        public string ADVBRNO;
        
        /// <remarks/>
        public string BIOFG;
        
        /// <remarks/>
        public string OUACFG;
        
        /// <remarks/>
        public string FCREBRN;
        
        /// <remarks/>
        public string FKEMPNO;
        
        /// <remarks/>
        public string FLTXDAY;
        
        /// <remarks/>
        public string FLBRNO;
        
        /// <remarks/>
        public string BASFG;
        
        /// <remarks/>
        public string FINAFG;
        
        /// <remarks/>
        public string LCBRNO;
        
        /// <remarks/>
        public string LCDAY;
        
        /// <remarks/>
        public string VIPFG;
        
        /// <remarks/>
        public string EXPDATE;
        
        /// <remarks/>
        public string NCIFKEY;
        
        /// <remarks/>
        public string NCIFERR;
        
        /// <remarks/>
        public string FOBRNO;
        
        /// <remarks/>
        public string FONO;
        
        /// <remarks/>
        public string FONAME;
        
        /// <remarks/>
        public string REGNUM;
        
        /// <remarks/>
        public string ADVEMAIL1;
        
        /// <remarks/>
        public string CONZIP1;
        
        /// <remarks/>
        public string CONADD1;
        
        /// <remarks/>
        public string ORGAN;
        
        /// <remarks/>
        public string RADDR1;
        
        /// <remarks/>
        public string RADDR2;
        
        /// <remarks/>
        public string RADDR3;
        
        /// <remarks/>
        public string RADDR4;
        
        /// <remarks/>
        public string FDATE;
        
        /// <remarks/>
        public string EDATE;
        
        /// <remarks/>
        public string AUTOFLAG;
        
        /// <remarks/>
        public string NETFLAG;
        
        /// <remarks/>
        public string BCODE2;
        
        /// <remarks/>
        public string EBKFG;
        
        /// <remarks/>
        public string BCODEX;
        
        /// <remarks/>
        public string CIFREASON;
        
        /// <remarks/>
        public string FUNDFG;
        
        /// <remarks/>
        public string CARDFG;
        
        /// <remarks/>
        public string BOXFG;
        
        /// <remarks/>
        public string TICKFG;
        
        /// <remarks/>
        public string CONBRN;
        
        /// <remarks/>
        public string GATEFG1;
        
        /// <remarks/>
        public string RPTBRNO;
        
        /// <remarks/>
        public string RMBFG;
        
        /// <remarks/>
        public string SPEFG;
        
        /// <remarks/>
        public string STAFFCODE;
        
        /// <remarks/>
        public string CORPFG;
        
        /// <remarks/>
        public string CORPID;
        
        /// <remarks/>
        public string CORPERR;
        
        /// <remarks/>
        public string PREMFG;
        
        /// <remarks/>
        public string PREMDAY;
        
        /// <remarks/>
        public string PREMEDAY;
    }
}
