//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EAI.Service.Transaction.L0105_Rs {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
        
        /// <remarks/>
        public string ErrCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PrcDt;
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRs MsgRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRs {
        
        /// <remarks/>
        public IFXEAIBodyMsgRsHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRsSvcRs SvcRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsHeader {
        
        /// <remarks/>
        public string TxnId;
        
        /// <remarks/>
        public string RecCtrlStatus;
        
        /// <remarks/>
        public string RspCode;
        
        /// <remarks/>
        public string Desc;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsSvcRs {
        
        /// <remarks/>
        public string BRNO;
        
        /// <remarks/>
        public string TRMSEQ;
        
        /// <remarks/>
        public string TXTNO;
        
        /// <remarks/>
        public string IBRNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string NAME;
        
        /// <remarks/>
        public string CNT;
        
        /// <remarks/>
        public string AMT;
        
        /// <remarks/>
        public string HAMT1;
        
        /// <remarks/>
        public string HAMT2;
        
        /// <remarks/>
        public string AOBRNO;
        
        /// <remarks/>
        public string AONO;
        
        /// <remarks/>
        public string TEL;
        
        /// <remarks/>
        public string BDAMT;
        
        /// <remarks/>
        public string DMAMT;
        
        /// <remarks/>
        public string LOBRNO;
        
        /// <remarks/>
        public string LONO;
        
        /// <remarks/>
        public string CLOBRNO;
        
        /// <remarks/>
        public string CLONO;
        
        /// <remarks/>
        public string LTRAMT;
        
        /// <remarks/>
        public string G4000AMT;
        
        /// <remarks/>
        public string CRGRAMT;
        
        /// <remarks/>
        public string CRGRGAMT;
        
        /// <remarks/>
        public string LCARBAL;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Detail")]
        public IFXEAIBodyMsgRsSvcRsDetail[] Detail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsSvcRsDetail {
        
        /// <remarks/>
        public string APNO;
        
        /// <remarks/>
        public string SRNO;
        
        /// <remarks/>
        public string CHKDG;
        
        /// <remarks/>
        public string SQNO;
        
        /// <remarks/>
        public string ACTBAL;
        
        /// <remarks/>
        public string APSDAY;
        
        /// <remarks/>
        public string APEDAY;
        
        /// <remarks/>
        public string OIDATE;
        
        /// <remarks/>
        public string IDATE;
        
        /// <remarks/>
        public string CHARCD1;
        
        /// <remarks/>
        public string CHARCD2;
        
        /// <remarks/>
        public string FITIRT;
        
        /// <remarks/>
        public string OACTBAL;
        
        /// <remarks/>
        public string XCRT;
        
        /// <remarks/>
        public string STATUS;
        
        /// <remarks/>
        public string LNCD;
        
        /// <remarks/>
        public string SINTFG;
        
        /// <remarks/>
        public string BRNO1;
        
        /// <remarks/>
        public string PRDATE;
        
        /// <remarks/>
        public string EXSDAY;
        
        /// <remarks/>
        public string CURCD;
        
        /// <remarks/>
        public string OCODE;
        
        /// <remarks/>
        public string APRNO;
        
        /// <remarks/>
        public string IRTCD;
        
        /// <remarks/>
        public string SURFLG;
        
        /// <remarks/>
        public string MGNO;
        
        /// <remarks/>
        public string LTYSTUS;
        
        /// <remarks/>
        public string ARBAL;
        
        /// <remarks/>
        public string APAMT;
        
        /// <remarks/>
        public string LOANFG;
        
        /// <remarks/>
        public string REFNO1;
        
        /// <remarks/>
        public string REFNO2;
        
        /// <remarks/>
        public string CRGRFLG;
        
        /// <remarks/>
        public string CRGRRATE;
        
        /// <remarks/>
        public string CRBRNO;
        
        /// <remarks/>
        public string CRAPNO;
        
        /// <remarks/>
        public string CRSRNO;
        
        /// <remarks/>
        public string CRCHKDG;
        
        /// <remarks/>
        public string CRSQNO;
        
        /// <remarks/>
        public string LOANFG1;
        
        /// <remarks/>
        public string FEEFG;
        
        /// <remarks/>
        public string FEDAY;

        public string RFNO;
    }
}
