//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EAI.Service.Transaction.L0104_Rs {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
        
        /// <remarks/>
        public string ErrCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PrcDt;
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRs MsgRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRs {
        
        /// <remarks/>
        public IFXEAIBodyMsgRsHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRsSvcRs SvcRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsHeader {
        
        /// <remarks/>
        public string TxnId;
        
        /// <remarks/>
        public string RecCtrlStatus;
        
        /// <remarks/>
        public string RspCode;
        
        /// <remarks/>
        public string Desc;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsSvcRs {
        
        /// <remarks/>
        public string ACTNO;
        
        /// <remarks/>
        public string NAME;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string INQSDAY;
        
        /// <remarks/>
        public string INQEDAY;
        
        /// <remarks/>
        public string ACNO;
        
        /// <remarks/>
        public string SBNO;
        
        /// <remarks/>
        public string ACTBAL;
        
        /// <remarks/>
        public string DMCD;
        
        /// <remarks/>
        public string APSDAY;
        
        /// <remarks/>
        public string APAMT;
        
        /// <remarks/>
        public string DMDATE;
        
        /// <remarks/>
        public string DMAMT;
        
        /// <remarks/>
        public string BDDATE;
        
        /// <remarks/>
        public string BDAMT;
        
        /// <remarks/>
        public string SINTFG;
        
        /// <remarks/>
        public string CLSID;
        
        /// <remarks/>
        public string CLSNO;
        
        /// <remarks/>
        public string SURFLG;
        
        /// <remarks/>
        public string APEDAY;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Detail")]
        public IFXEAIBodyMsgRsSvcRsDetail[] Detail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsSvcRsDetail {
        
        /// <remarks/>
        public string TXCD;
        
        /// <remarks/>
        public string IEDATE;
        
        /// <remarks/>
        public string TXDATE;
        
        /// <remarks/>
        public string FITIRT;
        
        /// <remarks/>
        public string TBSDY;
        
        /// <remarks/>
        public string TXSQ;
        
        /// <remarks/>
        public string PRIAMT;
        
        /// <remarks/>
        public string INTAMT;
        
        /// <remarks/>
        public string BAL;
        
        /// <remarks/>
        public string NTENF;
        
        /// <remarks/>
        public string DFAMT;
        
        /// <remarks/>
        public string EAMT;
        
        /// <remarks/>
        public string HCODE;
        
        /// <remarks/>
        public string BLRECFG;
        
        /// <remarks/>
        public string ISDAY;
        
        /// <remarks/>
        public string IEDAY;
        
        /// <remarks/>
        public string INTDAYS;
        
        /// <remarks/>
        public string DATETYP;
        
        /// <remarks/>
        public string DCIRAMT;
        
        /// <remarks/>
        public string PRIAMTD;
        
        /// <remarks/>
        public string INTAMTD;
        
        /// <remarks/>
        public string NHCODE;
        
        /// <remarks/>
        public string SVEFEE;
        
        /// <remarks/>
        public string DMNO;
        
        /// <remarks/>
        public string NOTE;
        
        /// <remarks/>
        public string FUNDBAL1;
        
        /// <remarks/>
        public string ARDLINT;

        public string ACTNO;

        public string CIFKEY;

        public string ACTBAL;
    }
}
