//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EAI.Service.Transaction.L1000_Rq {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string PrcDt;
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRq MsgRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRq {
        
        /// <remarks/>
        public IFXEAIBodyMsgRqHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRqSvcRq SvcRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqHeader {
        
        /// <remarks/>
        public string TxnId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqSvcRq {
        
        /// <remarks/>
        public string KINBR;
        
        /// <remarks/>
        public string ACTNO;
        
        /// <remarks/>
        public string HCODE;
        
        /// <remarks/>
        public string ECKIN;
        
        /// <remarks/>
        public string ECTRM;
        
        /// <remarks/>
        public string ECTNO;
        
        /// <remarks/>
        public string RBRNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string TXAMT;
        
        /// <remarks/>
        public string SEQFG;
        
        /// <remarks/>
        public string ACFLG;
        
        /// <remarks/>
        public string MGNO;
        
        /// <remarks/>
        public string ACNO;
        
        /// <remarks/>
        public string SBNO;
        
        /// <remarks/>
        public string GUNO;
        
        /// <remarks/>
        public string FUNCD;
        
        /// <remarks/>
        public string CHARCD1;
        
        /// <remarks/>
        public string CHARCD2;
        
        /// <remarks/>
        public string APSDAY;
        
        /// <remarks/>
        public string APEDAY;
        
        /// <remarks/>
        public string IMDAYS;
        
        /// <remarks/>
        public string IMMONS;
        
        /// <remarks/>
        public string PRCD;
        
        /// <remarks/>
        public string PRRATE;
        
        /// <remarks/>
        public string INTTM;
        
        /// <remarks/>
        public string INTTW;
        
        /// <remarks/>
        public string RATECD;
        
        /// <remarks/>
        public string IRTCD;
        
        /// <remarks/>
        public string IRTFT;
        
        /// <remarks/>
        public string SIGN;
        
        /// <remarks/>
        public string IXPR;
        
        /// <remarks/>
        public string FITIRT;
        
        /// <remarks/>
        public string IRTADJ;
        
        /// <remarks/>
        public string IRTDM;
        
        /// <remarks/>
        public string ISTFLG;
        
        /// <remarks/>
        public string PRTM;
        
        /// <remarks/>
        public string PRTW;
        
        /// <remarks/>
        public string IRTTM;
        
        /// <remarks/>
        public string CNIRDT;
        
        /// <remarks/>
        public string GRACEDAY;
        
        /// <remarks/>
        public string PRDATE;
        
        /// <remarks/>
        public string APTYPE;
        
        /// <remarks/>
        public string APACTNO;
        
        /// <remarks/>
        public string AUTCD;
        
        /// <remarks/>
        public string PAYACTNO;
        
        /// <remarks/>
        public string MGENO;
        
        /// <remarks/>
        public string SPENO;
        
        /// <remarks/>
        public string LNCD;
        
        /// <remarks/>
        public string NOTE;
        
        /// <remarks/>
        public string CRGRRATE;
        
        /// <remarks/>
        public string CRGRTYPE;
        
        /// <remarks/>
        public string YEAR;
        
        /// <remarks/>
        public string SIFLG;
        
        /// <remarks/>
        public string SINO;
        
        /// <remarks/>
        public string CRACTNO;
        
        /// <remarks/>
        public string INTRQSP;
        
        /// <remarks/>
        public string LABSTAT;
        
        /// <remarks/>
        public string RVSNO;
        
        /// <remarks/>
        public string INTEXT;
        
        /// <remarks/>
        public string BEGINFEE;
        
        /// <remarks/>
        public string TXTYPE;
        
        /// <remarks/>
        public string TAYACTNO;
        
        /// <remarks/>
        public string LOANTYP;
        
        /// <remarks/>
        public string GOVSTYP;
        
        /// <remarks/>
        public string ZEDFRATE;
        
        /// <remarks/>
        public string IRTKD;
        
        /// <remarks/>
        public string LCACTNO;
        
        /// <remarks/>
        public string LCDCNT;
        
        /// <remarks/>
        public string IDATE;
        
        /// <remarks/>
        public string SVEINT;
        
        /// <remarks/>
        public string PERINRATE;
        
        /// <remarks/>
        public string OFUNDAMT;
        
        /// <remarks/>
        public string REPYCD;
        
        /// <remarks/>
        public string REPYCDX;
        
        /// <remarks/>
        public string CONRATECD;
        
        /// <remarks/>
        public string FFIDATE;
        
        /// <remarks/>
        public string MORPRCD;
        
        /// <remarks/>
        public string ISHLD;
        
        /// <remarks/>
        public string HLDAMT;
        
        /// <remarks/>
        public string DFFLAG;
        
        /// <remarks/>
        public string NXREFNO;
        
        /// <remarks/>
        public string BTFLG;
        
        /// <remarks/>
        public string RULE;
        
        /// <remarks/>
        public string RULEX;
        
        /// <remarks/>
        public string FITLOW;
    }
}
