//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EAI.Service.Transaction.L1201_Rq {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRq MsgRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRq {
        
        /// <remarks/>
        public IFXEAIBodyMsgRqHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRqSvcRq SvcRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqHeader {
        
        /// <remarks/>
        public string TxnId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqSvcRq {
        
        /// <remarks/>
        public string KINBR;
        
        /// <remarks/>
        public string HCODE;
        
        /// <remarks/>
        public string ECKIN;
        
        /// <remarks/>
        public string ECTRM;
        
        /// <remarks/>
        public string ECTNO;
        
        /// <remarks/>
        public string LCACTNO;
        
        /// <remarks/>
        public string LCGTXNO;
        
        /// <remarks/>
        public string RBRNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string ACFLG;
        
        /// <remarks/>
        public string ACBRNO;
        
        /// <remarks/>
        public string MGDATA;
        
        /// <remarks/>
        public string ACTNO;
        
        /// <remarks/>
        public string IBGTXNO;
        
        /// <remarks/>
        public string TXAMT;
        
        /// <remarks/>
        public string CRGRRATE;
        
        /// <remarks/>
        public string CRGRTYPE;
        
        /// <remarks/>
        public string CRGRDT;
        
        /// <remarks/>
        public string EDAY;
        
        /// <remarks/>
        public string SDAY;
        
        /// <remarks/>
        public string CHARCD1;
        
        /// <remarks/>
        public string CHARCD2;
        
        /// <remarks/>
        public string ACNO;
        
        /// <remarks/>
        public string SBNO;
        
        /// <remarks/>
        public string BUNINO;
        
        /// <remarks/>
        public string IBKNO;
        
        /// <remarks/>
        public string IBRNO;
        
        /// <remarks/>
        public string HCRATE;
        
        /// <remarks/>
        public string HCFEE;
        
        /// <remarks/>
        public string TXTYPE;
        
        /// <remarks/>
        public string PACTNO;
        
        /// <remarks/>
        public string CKAMT;
        
        /// <remarks/>
        public string CKNO;
        
        /// <remarks/>
        public string CKBKNO7;
        
        /// <remarks/>
        public string CKACTNO;
        
        /// <remarks/>
        public string MGENO;
        
        /// <remarks/>
        public string SPENO;
        
        /// <remarks/>
        public string FUNCD;
        
        /// <remarks/>
        public string RVSNO;
        
        /// <remarks/>
        public string LOANTYP;
        
        /// <remarks/>
        public string GOVSTYP;
        
        /// <remarks/>
        public string SETGFG;
        
        /// <remarks/>
        public string GRAMT;
        
        /// <remarks/>
        public string ELCDTLFG;
        
        /// <remarks/>
        public string NEGRATE;
        
        /// <remarks/>
        public string NEGFEE;
    }
}
