//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.4084.0 自動產生。
// 
namespace EAI.Service.Transaction.L1203_Rq {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRq MsgRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRq {
        
        /// <remarks/>
        public IFXEAIBodyMsgRqHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRqSvcRq SvcRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqHeader {
        
        /// <remarks/>
        public string TxnId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqSvcRq {
        
        /// <remarks/>
        public string KINBR;
        
        /// <remarks/>
        public string HCODE;
        
        /// <remarks/>
        public string ECKIN;
        
        /// <remarks/>
        public string ECTRM;
        
        /// <remarks/>
        public string ECTNO;
        
        /// <remarks/>
        public string RBRNO;
        
        /// <remarks/>
        public string SBRNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string MGDATA;
        
        /// <remarks/>
        public string ACTNO;
        
        /// <remarks/>
        public string CHARCD1;
        
        /// <remarks/>
        public string CHARCD2;
        
        /// <remarks/>
        public string ACNO;
        
        /// <remarks/>
        public string SBNO;
        
        /// <remarks/>
        public string SDAY;
        
        /// <remarks/>
        public string GRAMT;
        
        /// <remarks/>
        public string EDAY;
        
        /// <remarks/>
        public string RTDAY;
        
        /// <remarks/>
        public string NOTEBK;
        
        /// <remarks/>
        public string BUNINO;
        
        /// <remarks/>
        public string ISDAYCNT;
        
        /// <remarks/>
        public string RATE;
        
        /// <remarks/>
        public string FEE;
        
        /// <remarks/>
        public string HCRATE;
        
        /// <remarks/>
        public string HCFEE;
        
        /// <remarks/>
        public string TXTYPE;
        
        /// <remarks/>
        public string PACTNO;
        
        /// <remarks/>
        public string CKAMT;
        
        /// <remarks/>
        public string CKNO;
        
        /// <remarks/>
        public string CKBKNO7;
        
        /// <remarks/>
        public string CKACTNO;
        
        /// <remarks/>
        public string FUNCD;
        
        /// <remarks/>
        public string MGENO;
        
        /// <remarks/>
        public string SPENO;
        
        /// <remarks/>
        public string PAYNO;
        
        /// <remarks/>
        public string PAYTYPE;
        
        /// <remarks/>
        public string PAYDAY;
        
        /// <remarks/>
        public string SEAL;
        
        /// <remarks/>
        public string DELIVER;
        
        /// <remarks/>
        public string CONT1;
        
        /// <remarks/>
        public string CONT2;
        
        /// <remarks/>
        public string CONT3;
        
        /// <remarks/>
        public string DEADLE;
        
        /// <remarks/>
        public string GTXNO;
        
        /// <remarks/>
        public string RVSNO;
        
        /// <remarks/>
        public string LOANTYP;
        
        /// <remarks/>
        public string GOVSTYP;
        
        /// <remarks/>
        public string SETGFG;
        
        /// <remarks/>
        public string TYPE;
        
        /// <remarks/>
        public string FSQAMT;
        
        /// <remarks/>
        public string FCURCD;
        
        /// <remarks/>
        public string EXRATE;
        
        /// <remarks/>
        public string TXAMT;
        
        /// <remarks/>
        public string ELCDTLFG;
        
        /// <remarks/>
        public string ACFLG;
        
        /// <remarks/>
        public string PRODNM1;
        
        /// <remarks/>
        public string PRODSPEC1;
        
        /// <remarks/>
        public string PRODAMT1;
        
        /// <remarks/>
        public string PRODQ1;
        
        /// <remarks/>
        public string PRODTAMT1;
        
        /// <remarks/>
        public string PRODNM2;
        
        /// <remarks/>
        public string PRODSPEC2;
        
        /// <remarks/>
        public string PRODAMT2;
        
        /// <remarks/>
        public string PRODQ2;
        
        /// <remarks/>
        public string PRODTAMT2;
        
        /// <remarks/>
        public string PRODNM3;
        
        /// <remarks/>
        public string PRODSPEC3;
        
        /// <remarks/>
        public string PRODAMT3;
        
        /// <remarks/>
        public string PRODQ3;
        
        /// <remarks/>
        public string PRODTAMT3;
        
        /// <remarks/>
        public string PRODNM4;
        
        /// <remarks/>
        public string PRODSPEC4;
        
        /// <remarks/>
        public string PRODAMT4;
        
        /// <remarks/>
        public string PRODQ4;
        
        /// <remarks/>
        public string PRODTAMT4;
        
        /// <remarks/>
        public string PRODNM5;
        
        /// <remarks/>
        public string PRODSPEC5;
        
        /// <remarks/>
        public string PRODAMT5;
        
        /// <remarks/>
        public string PRODQ5;
        
        /// <remarks/>
        public string PRODTAMT5;
        
        /// <remarks/>
        public string PRODNM6;
        
        /// <remarks/>
        public string PRODSPEC6;
        
        /// <remarks/>
        public string PRODAMT6;
        
        /// <remarks/>
        public string PRODQ6;
        
        /// <remarks/>
        public string PRODTAMT6;
        
        /// <remarks/>
        public string CRGRRATE;
        
        /// <remarks/>
        public string CRGRTYPE;
        
        /// <remarks/>
        public string CRGRDT;
        
        /// <remarks/>
        public string CRGRAMT;
        
        /// <remarks/>
        public string PAYDATE;
        
        /// <remarks/>
        public string SINO;
        
        /// <remarks/>
        public string GUNO;
    }
}
