//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18034
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.0.30319.1 自動產生。
// 
namespace EAI.Service.Transaction.L3700_Rq {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRq MsgRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRq {
        
        /// <remarks/>
        public IFXEAIBodyMsgRqHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRqSvcRq SvcRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqHeader {
        
        /// <remarks/>
        public string TxnId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqSvcRq {
        
        /// <remarks/>
        public string KINBR;
        
        /// <remarks/>
        public string HCODE;
        
        /// <remarks/>
        public string ECKIN;
        
        /// <remarks/>
        public string ECTRM;
        
        /// <remarks/>
        public string ECTNO;
        
        /// <remarks/>
        public string ACTNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string ITEM;
        
        /// <remarks/>
        public string SQAMT;
        
        /// <remarks/>
        public string DATE;
        
        /// <remarks/>
        public string CAUSE;
        
        /// <remarks/>
        public string RTDATE;
        
        /// <remarks/>
        public string RTCAUSE;
        
        /// <remarks/>
        public string GRAMT;
        
        /// <remarks/>
        public string CHRATE;
        
        /// <remarks/>
        public string FEE;
        
        /// <remarks/>
        public string HCFEE;
        
        /// <remarks/>
        public string TXTYPE;
        
        /// <remarks/>
        public string PACTNO;
        
        /// <remarks/>
        public string FSQAMT;
        
        /// <remarks/>
        public string FCURCD;
        
        /// <remarks/>
        public string EXRATE;
        
        /// <remarks/>
        public string CKAMT;
        
        /// <remarks/>
        public string CKNO;
        
        /// <remarks/>
        public string CKBKNO7;
        
        /// <remarks/>
        public string CKACTNO;
        
        /// <remarks/>
        public string SEQFG;
        
        /// <remarks/>
        public string ACFLG;
        
        /// <remarks/>
        public string RVSYEAR;
        
        /// <remarks/>
        public string RVSSRNO;
    }
}
