//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.3928.0 自動產生。
// 
namespace EAI.Service.Transaction.L4200_Rq {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string PrcDt;
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRq MsgRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRq {
        
        /// <remarks/>
        public IFXEAIBodyMsgRqHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRqSvcRq SvcRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqHeader {
        
        /// <remarks/>
        public string TxnId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqSvcRq {
        
        /// <remarks/>
        public string KINBR;
        
        /// <remarks/>
        public string ACBRNO;
        
        /// <remarks/>
        public string ACFLG;
        
        /// <remarks/>
        public string HCODE;
        
        /// <remarks/>
        public string ECKIN;
        
        /// <remarks/>
        public string ECTRM;
        
        /// <remarks/>
        public string ECTNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string ACTNO;
        
        /// <remarks/>
        public string PRIAMT;
        
        /// <remarks/>
        public string VLDATE;
        
        /// <remarks/>
        public string SINTAMT;
        
        /// <remarks/>
        public string CREAMT;
        
        /// <remarks/>
        public string REFAMT;
        
        /// <remarks/>
        public string DFCD;
        
        /// <remarks/>
        public string INTAMT;
        
        /// <remarks/>
        public string DFAMT;
        
        /// <remarks/>
        public string EAMT;
        
        /// <remarks/>
        public string RECAMT;
        
        /// <remarks/>
        public string CAUSE;
        
        /// <remarks/>
        public string TXTYPE;
        
        /// <remarks/>
        public string PAYACTNO;
        
        /// <remarks/>
        public string CKAMT;
        
        /// <remarks/>
        public string CKNO;
        
        /// <remarks/>
        public string CKBKNO;
        
        /// <remarks/>
        public string CKACTNO;
        
        /// <remarks/>
        public string EAMTCD;
        
        /// <remarks/>
        public string LNSDFAMT;
        
        /// <remarks/>
        public string BLRECFG;
        
        /// <remarks/>
        public string CLSID;
        
        /// <remarks/>
        public string CLSNO;
        
        /// <remarks/>
        public string CANCEL;
        
        /// <remarks/>
        public string BACKINT;
        
        /// <remarks/>
        public string AXTYPE;
        
        /// <remarks/>
        public string APACTNO;
        
        /// <remarks/>
        public string REASON1;
        
        /// <remarks/>
        public string REASON2;
        
        /// <remarks/>
        public string REASON3;
        
        /// <remarks/>
        public string UCIFKEY;
        
        /// <remarks/>
        public string REPYCD;
        
        /// <remarks/>
        public string REPYCDX;
        
        /// <remarks/>
        public string BDAMT;
        
        /// <remarks/>
        public string RVSNO;
        
        /// <remarks/>
        public string TDLINT;
        
        /// <remarks/>
        public string DLCD;
        
        /// <remarks/>
        public string ADLINT;
        
        /// <remarks/>
        public string ETX;
    }
}
