//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.4084.0 自動產生。
// 
namespace EAI.Service.Transaction.LR017_Rs {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string DebugLevel;
        
        /// <remarks/>
        public string ErrCode;
        
        /// <remarks/>
        public string RecSize;
        
        /// <remarks/>
        public string DomID;
        
        /// <remarks/>
        public string TimeOut;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string Capacity;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string TxnID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRs MsgRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRs {
        
        /// <remarks/>
        public IFXEAIBodyMsgRsHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRsSvcRs SvcRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsHeader {
        
        /// <remarks/>
        public string TxnId;
        
        /// <remarks/>
        public string RspCode;
        
        /// <remarks/>
        public string Desc;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsSvcRs {
        
        /// <remarks/>
        public string BRNO;
        
        /// <remarks/>
        public string TRMSEQ;
        
        /// <remarks/>
        public string TXTNO;
        
        /// <remarks/>
        public string APNO;
        
        /// <remarks/>
        public string SRNO;
        
        /// <remarks/>
        public string CHKDG;
        
        /// <remarks/>
        public string SQNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string ACNO;
        
        /// <remarks/>
        public string SBNO;
        
        /// <remarks/>
        public string CHARCD1;
        
        /// <remarks/>
        public string CHARCD2;
        
        /// <remarks/>
        public string SDAY;
        
        /// <remarks/>
        public string EDAY;
        
        /// <remarks/>
        public string LASTDT;
        
        /// <remarks/>
        public string RTDAY;
        
        /// <remarks/>
        public string CRGRRATE;
        
        /// <remarks/>
        public string CRGRTYPE;
        
        /// <remarks/>
        public string CRGRDT;
        
        /// <remarks/>
        public string SQAMT;
        
        /// <remarks/>
        public string SQBAL;
        
        /// <remarks/>
        public string GRAMT;
        
        /// <remarks/>
        public string GRBAL;
        
        /// <remarks/>
        public string ARBAL;
        
        /// <remarks/>
        public string ACPCD;
        
        /// <remarks/>
        public string NOTEBK;
        
        /// <remarks/>
        public string BCIFKEY;
        
        /// <remarks/>
        public string BCIFERR;
        
        /// <remarks/>
        public string ISDAYCNT;
        
        /// <remarks/>
        public string RATE;
        
        /// <remarks/>
        public string FEE;
        
        /// <remarks/>
        public string CHRATE;
        
        /// <remarks/>
        public string CHFEE;
        
        /// <remarks/>
        public string HCRATE;
        
        /// <remarks/>
        public string HCFEE;
        
        /// <remarks/>
        public string FUNCD;
        
        /// <remarks/>
        public string DMPNO;
        
        /// <remarks/>
        public string DMUNO;
        
        /// <remarks/>
        public string DECODE;
        
        /// <remarks/>
        public string DEBKNO;
        
        /// <remarks/>
        public string ACTCD;
        
        /// <remarks/>
        public string MGBRNO;
        
        /// <remarks/>
        public string MGAPNO;
        
        /// <remarks/>
        public string MGSBNO;
        
        /// <remarks/>
        public string MGSRNO;
        
        /// <remarks/>
        public string IBKNO;
        
        /// <remarks/>
        public string IBRNO;
        
        /// <remarks/>
        public string RBRNO;
        
        /// <remarks/>
        public string SBRNO;
        
        /// <remarks/>
        public string SPCD;
        
        /// <remarks/>
        public string MGENO;
        
        /// <remarks/>
        public string SPENO;
        
        /// <remarks/>
        public string DMCD;
        
        /// <remarks/>
        public string OCODE;
        
        /// <remarks/>
        public string MNCNT;
        
        /// <remarks/>
        public string DTCNT;
        
        /// <remarks/>
        public string PAYNO;
        
        /// <remarks/>
        public string PAYTYPE;
        
        /// <remarks/>
        public string PAYDAY;
        
        /// <remarks/>
        public string CONT1;
        
        /// <remarks/>
        public string CONT2;
        
        /// <remarks/>
        public string CONT3;
        
        /// <remarks/>
        public string SEAL;
        
        /// <remarks/>
        public string DELIVER;
        
        /// <remarks/>
        public string DEADL;
        
        /// <remarks/>
        public string VRATE;
        
        /// <remarks/>
        public string VINT;
        
        /// <remarks/>
        public string NVINT;
        
        /// <remarks/>
        public string VDFAMT;
        
        /// <remarks/>
        public string NVDFAMT;
        
        /// <remarks/>
        public string EMPNOT;
        
        /// <remarks/>
        public string EMPNOS;
        
        /// <remarks/>
        public string VDATE;
        
        /// <remarks/>
        public string CONVFG;
        
        /// <remarks/>
        public string CURCD;
        
        /// <remarks/>
        public string LOANTYP;
        
        /// <remarks/>
        public string GOVSTYP;
        
        /// <remarks/>
        public string SETGFG;
        
        /// <remarks/>
        public string LCBRNO;
        
        /// <remarks/>
        public string LCAPNO;
        
        /// <remarks/>
        public string LCSRNO;
        
        /// <remarks/>
        public string LCCHKDG;
        
        /// <remarks/>
        public string LCSQNO;
        
        /// <remarks/>
        public string TYPE;
        
        /// <remarks/>
        public string FCURCD;
        
        /// <remarks/>
        public string FSQAMT;
        
        /// <remarks/>
        public string EXRATE;
        
        /// <remarks/>
        public string FSQBAL;
        
        /// <remarks/>
        public string ELCDTLFG;
        
        /// <remarks/>
        public string GTXNO;
        
        /// <remarks/>
        public string GUNO;
    }
}
