//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace EAI.Service.Transaction.P1002_Rs {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
        
        /// <remarks/>
        public string ErrCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRs MsgRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRs {
        
        /// <remarks/>
        public IFXEAIBodyMsgRsHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRsSvcRs SvcRs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsHeader {
        
        /// <remarks/>
        public string TxnId;
        
        /// <remarks/>
        public string RspCode;
        
        /// <remarks/>
        public string Desc;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRsSvcRs {
        
        /// <remarks/>
        public string BRNO;
        
        /// <remarks/>
        public string TRMSEQ;
        
        /// <remarks/>
        public string TXTNO;
        
        /// <remarks/>
        public string TPFG;
        
        /// <remarks/>
        public string CBDAY;
        
        /// <remarks/>
        public string ACTBAL;
        
        /// <remarks/>
        public string AVBAL;
        
        /// <remarks/>
        public string NBCNT;
        
        /// <remarks/>
        public string CHAMT;
        
        /// <remarks/>
        public string CDWAMT;
        
        /// <remarks/>
        public ulong REFNO;
        
        /// <remarks/>
        public string CNAME;
        
        /// <remarks/>
        public string SEX;
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public ulong OACTNO;
        
        /// <remarks/>
        public string IACTNO;
        
        /// <remarks/>
        public string TXAMT;
        
        /// <remarks/>
        public string FEEBYWHO;
        
        /// <remarks/>
        public string CDSTAN;
        
        /// <remarks/>
        public string TXMEMO;
        
        /// <remarks/>
        public string TXTIME;
        
        /// <remarks/>
        public string TXDATE;
        
        /// <remarks/>
        public string AMT;
        
        /// <remarks/>
        public string OBANKID;
        
        /// <remarks/>
        public string RCVNAME;
        
        /// <remarks/>
        public string EDIID;
        
        /// <remarks/>
        public string EDINODE;
        
        /// <remarks/>
        public string EBKFG;
        
        /// <remarks/>
        public string PFG;
    }
}
