//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace EAI.Service.Transaction.P1000_Rq {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ifxforum.org", IsNullable=false)]
    public partial class IFX {
        
        /// <remarks/>
        public IFXEAIHeader EAIHeader;
        
        /// <remarks/>
        public IFXLogTxn LogTxn;
        
        /// <remarks/>
        public IFXEAIBody EAIBody;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIHeader {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string RecID;
        
        /// <remarks/>
        public string SrcSystemID;
        
        /// <remarks/>
        public string DomID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXLogTxn {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public string PrcDt;
        
        /// <remarks/>
        public string PmtID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBody {
        
        /// <remarks/>
        public IFXEAIBodyMsgRq MsgRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRq {
        
        /// <remarks/>
        public IFXEAIBodyMsgRqHeader Header;
        
        /// <remarks/>
        public IFXEAIBodyMsgRqSvcRq SvcRq;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqHeader {
        
        /// <remarks/>
        public string TxnId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ifxforum.org")]
    public partial class IFXEAIBodyMsgRqSvcRq {
        
        /// <remarks/>
        public string KINBR;
        
        /// <remarks/>
        public string ACBRNO;
        
        /// <remarks/>
        public string CIFKEY;
        
        /// <remarks/>
        public string CIFERR;
        
        /// <remarks/>
        public string ACFLG;
        
        /// <remarks/>
        public string PBVER;
        
        /// <remarks/>
        public string PBPAGE;
        
        /// <remarks/>
        public string PBCOL;
        
        /// <remarks/>
        public string SPBBAL;
        
        /// <remarks/>
        public string PBBAL;
        
        /// <remarks/>
        public string MSRCD;
        
        /// <remarks/>
        public string TXTYPE;
        
        /// <remarks/>
        public string TXMEMO;
        
        /// <remarks/>
        public string BDTXD;
        
        /// <remarks/>
        public string PASWD;
        
        /// <remarks/>
        public string IMACTNO;
        
        /// <remarks/>
        public string CMAFG;
        
        /// <remarks/>
        public string CODEDPNR;
        
        /// <remarks/>
        public string CODEDD;
        
        /// <remarks/>
        public string RGDAY;
        
        /// <remarks/>
        public string TRNSEQ;
        
        /// <remarks/>
        public string OTXTNO;
        
        /// <remarks/>
        public string PAACT;
        
        /// <remarks/>
        public string OPTIME;
        
        /// <remarks/>
        public string OPBAT;
        
        /// <remarks/>
        public string OPNO;
        
        /// <remarks/>
        public string OPACNR;
        
        /// <remarks/>
        public string OPTYPE;
        
        /// <remarks/>
        public string ORGAMT;
        
        /// <remarks/>
        public string OACBRNO;
        
        /// <remarks/>
        public string AUTHCODE;
        
        /// <remarks/>
        public string NBBHNO;
        
        /// <remarks/>
        public string NBBHSEQ;
        
        /// <remarks/>
        public string CMPNAME;
        
        /// <remarks/>
        public string CMPUNINO;
        
        /// <remarks/>
        public string AGTYPE;
        
        /// <remarks/>
        public string DSCPTFG;
        
        /// <remarks/>
        public string SECNO1;
        
        /// <remarks/>
        public string ETX;
        
        /// <remarks/>
        public string BIOSECNO1;
        
        /// <remarks/>
        public string BIOETX;
        
        /// <remarks/>
        public string APSECNO;
        
        /// <remarks/>
        public string OBRNO;
        
        /// <remarks/>
        public string IMAGEFG;
        
        /// <remarks/>
        public string OTXTNO1;
        
        /// <remarks/>
        public string RMEMO;
        
        /// <remarks/>
        public string R8XMEMO;
        
        /// <remarks/>
        public string EKINBR;
        
        /// <remarks/>
        public string ETRMSEQ;
        
        /// <remarks/>
        public string ETXTNO;
        
        /// <remarks/>
        public string SRVAMT;
        
        /// <remarks/>
        public string STXTYPE;
        
        /// <remarks/>
        public string TRACTNO;
    }
}
