//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.4084.0 自動產生。
// 
namespace ModelCore.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class LLC {
        
        /// <remarks/>
        public LLCLC LC;
        
        /// <remarks/>
        public LLCLcAdvice LcAdvice;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        public LLCApplyLcNo ApplyLcNo;
        
        /// <remarks/>
        public LLCLcCancel LcCancel;
        
        /// <remarks/>
        public LLCReject Reject;
        
        /// <remarks/>
        public LLCAllowedNego AllowedNego;
        
        /// <remarks/>
        public LLCRejectedNego RejectedNego;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LLCLC {
        
        /// <remarks/>
        public string AppNo;
        
        /// <remarks/>
        public string AppDate;
        
        /// <remarks/>
        public string LcNo;
        
        /// <remarks/>
        public string IssuingDate;
        
        /// <remarks/>
        public string AdvisingBank;
        
        /// <remarks/>
        public string IssuingBank;
        
        /// <remarks/>
        public string PayableBank;
        
        /// <remarks/>
        public string Applicant;
        
        /// <remarks/>
        public string LcAmt;
        
        /// <remarks/>
        public string LcExpiry;
        
        /// <remarks/>
        public string AdvisingBankName;
        
        /// <remarks/>
        public string ReceiptNo;
        
        /// <remarks/>
        public string Beneficiary;
        
        /// <remarks/>
        public string ApplicantAddr;
        
        /// <remarks/>
        public string PayableBankName;
        
        /// <remarks/>
        public string PayableBankAddr;
        
        /// <remarks/>
        public string AtSight;
        
        /// <remarks/>
        public string AtUsance;
        
        /// <remarks/>
        public string Usance;
        
        /// <remarks/>
        public string AttachPaying;
        
        /// <remarks/>
        public string AttachAcceptance;
        
        /// <remarks/>
        public string AttachInv;
        
        /// <remarks/>
        public string Goods;
        
        /// <remarks/>
        public string Seal;
        
        /// <remarks/>
        public string BeneSeal;
        
        /// <remarks/>
        public string Partial;
        
        /// <remarks/>
        public string NonPatial;
        
        /// <remarks/>
        public string NoAfterThan;
        
        /// <remarks/>
        public string EarlyInvDate;
        
        /// <remarks/>
        public string LargerInvAmt;
        
        /// <remarks/>
        public string BeneficiaryNo;
        
        /// <remarks/>
        public string PaymentDate;
        
        /// <remarks/>
        public string AcceptEInv;
        
        /// <remarks/>
        public string AttachOthers;
        
        /// <remarks/>
        public string InvDateStart;
        
        /// <remarks/>
        public string NegoDateStart;
        
        /// <remarks/>
        public string AcceptInvAddr;
        
        /// <remarks/>
        public string AcceptInvDetails;
        
        /// <remarks/>
        public string AttachEInv;
        
        /// <remarks/>
        public string LargerInvNego;
        
        /// <remarks/>
        public string SpecificOthers;
        
        /// <remarks/>
        public string BankID;
        
        /// <remarks/>
        public string PdfBase64;
        
        /// <remarks/>
        public string ToConfirm;
        
        /// <remarks/>
        public string Committed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LLCLcAdvice {
        
        /// <remarks/>
        public string AppNo;
        
        /// <remarks/>
        public string AmendNo;
        
        /// <remarks/>
        public string AdviceNo;
        
        /// <remarks/>
        public string AdviceDate;
        
        /// <remarks/>
        public string LcNo;
        
        /// <remarks/>
        public string LcAmt;
        
        /// <remarks/>
        public string LcExpiry;
        
        /// <remarks/>
        public string Usance;
        
        /// <remarks/>
        public string AttachPaying;
        
        /// <remarks/>
        public string AttachAcceptance;
        
        /// <remarks/>
        public string AttachInv;
        
        /// <remarks/>
        public string Goods;
        
        /// <remarks/>
        public string Seal;
        
        /// <remarks/>
        public string BeneSeal;
        
        /// <remarks/>
        public string Partial;
        
        /// <remarks/>
        public string NoAfterThan;
        
        /// <remarks/>
        public string EarlyInvDate;
        
        /// <remarks/>
        public string LargerInvAmt;
        
        /// <remarks/>
        public string PaymentDate;
        
        /// <remarks/>
        public string AcceptEInv;
        
        /// <remarks/>
        public string AttachOthers;
        
        /// <remarks/>
        public string InvDateStart;
        
        /// <remarks/>
        public string NegoDateStart;
        
        /// <remarks/>
        public string AcceptInvAddr;
        
        /// <remarks/>
        public string AcceptInvDetails;
        
        /// <remarks/>
        public string AttachEInv;
        
        /// <remarks/>
        public string LargerInvNego;
        
        /// <remarks/>
        public string SpecificOthers;
        
        /// <remarks/>
        public string BankID;
        
        /// <remarks/>
        public string IssuingBank;
        
        /// <remarks/>
        public string ReceiptNo;
        
        /// <remarks/>
        public string PdfBase64;
        
        /// <remarks/>
        public string ToConfirm;
        
        /// <remarks/>
        public string Committed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LLCApplyLcNo {
        
        /// <remarks/>
        public string ApplNo;
        
        /// <remarks/>
        public string LcNo;
        
        /// <remarks/>
        public string AmendNo;
        
        /// <remarks/>
        public string CancelNo;
        
        /// <remarks/>
        public string CancelDate;
        
        /// <remarks/>
        public string BankID;
        
        /// <remarks/>
        public string IssuingBank;
        
        /// <remarks/>
        public string ReceiptNo;
        
        /// <remarks/>
        public string PdfBase64;
        
        /// <remarks/>
        public string ToConfirm;
        
        /// <remarks/>
        public string Committed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LLCLcCancel {
        
        /// <remarks/>
        public string ApplNo;
        
        /// <remarks/>
        public string LcNo;
        
        /// <remarks/>
        public string AmendNo;
        
        /// <remarks/>
        public string CancelNo;
        
        /// <remarks/>
        public string CancelDate;
        
        /// <remarks/>
        public string BankID;
        
        /// <remarks/>
        public string IssuingBank;
        
        /// <remarks/>
        public string ReceiptNo;
        
        /// <remarks/>
        public string PdfBase64;
        
        /// <remarks/>
        public string ToConfirm;
        
        /// <remarks/>
        public string Committed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LLCReject {
        
        /// <remarks/>
        public byte Code;
        
        /// <remarks/>
        public string Reason;
        
        /// <remarks/>
        public string BankID;
        
        /// <remarks/>
        public string ToConfirm;
        
        /// <remarks/>
        public string Committed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LLCAllowedNego {
        
        /// <remarks/>
        public string DraftNo;
        
        /// <remarks/>
        public string LcNo;
        
        /// <remarks/>
        public string BankID;
        
        /// <remarks/>
        public string ToConfirm;
        
        /// <remarks/>
        public string Committed;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class LLCRejectedNego {
        
        /// <remarks/>
        public string DraftNo;
        
        /// <remarks/>
        public string LcNo;
        
        /// <remarks/>
        public string BankID;
        
        /// <remarks/>
        public string ToConfirm;
        
        /// <remarks/>
        public string Committed;
    }
}
