//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace EAI.BSNS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BlueStar {
        
        /// <remarks/>
        public string BSNS_TelegramSource;
        
        /// <remarks/>
        public string BSNS_ProductID;
        
        /// <remarks/>
        public string BSNS_NotificationClassID;
        
        /// <remarks/>
        public string BSNS_CustomerID;
        
        /// <remarks/>
        public string BSNS_CustomerName;
        
        /// <remarks/>
        public string BSNS_AccountNumber;
        
        /// <remarks/>
        public string BSNS_AccountCurrency;
        
        /// <remarks/>
        public string BSNS_TFACode;
        
        /// <remarks/>
        public string BSNS_TxnDate;
        
        /// <remarks/>
        public string BSNS_SentDate;
        
        /// <remarks/>
        public string BSNS_SentTime;
        
        /// <remarks/>
        public string BSNS_JournalSeqNO;
        
        /// <remarks/>
        public string Branch;
        
        /// <remarks/>
        public string BSNS_IsBypassBSNS;
        
        /// <remarks/>
        public string ScheduledSendTime;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("BSNS_ContactWindow", IsNullable=false)]
        public BlueStarBSNS_ContactWindow[] BSNS_ContactWindowSet;
        
        /// <remarks/>
        public string NotificationTitle;
        
        /// <remarks/>
        public string ContentText;
        
        /// <remarks/>
        public BlueStarContentXML ContentXML;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attachment", IsNullable=false)]
        public BlueStarAttachment[] Attachments;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MsgName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string App;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarBSNS_ContactWindow {
        
        /// <remarks/>
        public string BSNS_DeliveryChannel;
        
        /// <remarks/>
        public string BSNS_ContactName;
        
        /// <remarks/>
        public string BSNS_ContactAddress;
        
        /// <remarks/>
        public string BSNS_Language;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarContentXML {
        
        /// <remarks/>
        public string Head;
        
        /// <remarks/>
        public string Body;
        
        /// <remarks/>
        public BlueStarContentXMLNotificationInfo NotificationInfo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarContentXMLNotificationInfo {
        
        /// <remarks/>
        public BlueStarContentXMLNotificationInfoContactInfo ContactInfo;
        
        /// <remarks/>
        public BlueStarContentXMLNotificationInfoMessage Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarContentXMLNotificationInfoContactInfo {
        
        /// <remarks/>
        public string TxnID;
        
        /// <remarks/>
        public BlueStarContentXMLNotificationInfoContactInfoFrom From;
        
        /// <remarks/>
        public BlueStarContentXMLNotificationInfoContactInfoTO To;
        
        /// <remarks/>
        public string Subject;
        
        /// <remarks/>
        public string TxnDate;
        
        /// <remarks/>
        public string TxnTime;
        
        /// <remarks/>
        public string Severity;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarContentXMLNotificationInfoContactInfoFrom {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string ID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarContentXMLNotificationInfoContactInfoTO {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string ID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarContentXMLNotificationInfoMessage {
        
        /// <remarks/>
        public string TextMessage;
        
        /// <remarks/>
        public BlueStarContentXMLNotificationInfoMessageInfoMessage InfoMessage;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarContentXMLNotificationInfoMessageInfoMessage {
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public string MainMsg;
        
        /// <remarks/>
        public string WarnMsg;
        
        /// <remarks/>
        public string OtherMsg;
        
        /// <remarks/>
        public string AddMsg;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BlueStarAttachment {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }
}
