//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 
namespace ModelCore.Schema.ENID {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.uxcds.com/xmlschema/cds", IsNullable=false)]
    public partial class CDSLcdCancellation {
        
        private LcdCancInfoType lcCancInfoField;
        
        private LcdType lcDocField;
        
        private LcdCancDataType lcCancDataField;
        
        private string versionField;
        
        /// <remarks/>
        public LcdCancInfoType lcCancInfo {
            get {
                return this.lcCancInfoField;
            }
            set {
                this.lcCancInfoField = value;
            }
        }
        
        /// <remarks/>
        public LcdType lcDoc {
            get {
                return this.lcDocField;
            }
            set {
                this.lcDocField = value;
            }
        }
        
        /// <remarks/>
        public LcdCancDataType lcCancData {
            get {
                return this.lcCancDataField;
            }
            set {
                this.lcCancDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
}
