//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 
namespace ModelCore.Schema.ENID {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.uxcds.com/xmlschema/cds", IsNullable=false)]
    public partial class CDSLcdReply {
        
        private LcdReplyInfoType lcReplyInfoField;
        
        private LcdReplyDataType lcReplyDataField;
        
        private string versionField;
        
        /// <remarks/>
        public LcdReplyInfoType lcReplyInfo {
            get {
                return this.lcReplyInfoField;
            }
            set {
                this.lcReplyInfoField = value;
            }
        }
        
        /// <remarks/>
        public LcdReplyDataType lcReplyData {
            get {
                return this.lcReplyDataField;
            }
            set {
                this.lcReplyDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
}
