//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 
namespace ModelCore.Schema.ENID {
    using System.Xml.Serialization;
   
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.uxcds.com/xmlschema/cds", IsNullable=false)]
    public partial class CDSLcd {
        
        private LcdInfoType lcInfoField;
        
        private LcdType lcDocField;
        
        private CPType cpDocField;
        
        private LcdDataType lcDataField;
        
        private string versionField;
        
        /// <remarks/>
        public LcdInfoType lcInfo {
            get {
                return this.lcInfoField;
            }
            set {
                this.lcInfoField = value;
            }
        }
        
        /// <remarks/>
        public LcdType lcDoc {
            get {
                return this.lcDocField;
            }
            set {
                this.lcDocField = value;
            }
        }
        
        /// <remarks/>
        public CPType cpDoc {
            get {
                return this.cpDocField;
            }
            set {
                this.cpDocField = value;
            }
        }
        
        /// <remarks/>
        public LcdDataType lcData {
            get {
                return this.lcDataField;
            }
            set {
                this.lcDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
}
