//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 
namespace ModelCore.Schema.ENID {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.uxcds.com/xmlschema/cds", IsNullable=false)]
    public partial class allConditions {
        
        private allConditionsConditionGroup[] conditionGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conditionGroup")]
        public allConditionsConditionGroup[] conditionGroup {
            get {
                return this.conditionGroupField;
            }
            set {
                this.conditionGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class allConditionsConditionGroup {
        
        private conditionsCondition[] conditionsField;
        
        private string nameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("condition", IsNullable=false)]
        public conditionsCondition[] conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class conditionsCondition {
        
        private string titleField;
        
        private string descriptionField;
        
        private string[] prefixMessageField;
        
        private SingleChoiceType singleChoiceField;
        
        private MultiChoiceType multiChoiceField;
        
        private TextBlankType textBlankField;
        
        private TextAreaType textAreaField;
        
        private TextOnlyType textOnlyField;
        
        private string[] suffixMessageField;
        
        private string nameField;
        
        private conditionsConditionPresent presentField;
        
        private conditionsConditionType typeField;
        
        private conditionsConditionUsed usedField;
        
        private conditionsConditionChanged changedField;
        
        private bool changedFieldSpecified;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("prefixMessage")]
        public string[] prefixMessage {
            get {
                return this.prefixMessageField;
            }
            set {
                this.prefixMessageField = value;
            }
        }
        
        /// <remarks/>
        public SingleChoiceType singleChoice {
            get {
                return this.singleChoiceField;
            }
            set {
                this.singleChoiceField = value;
            }
        }
        
        /// <remarks/>
        public MultiChoiceType multiChoice {
            get {
                return this.multiChoiceField;
            }
            set {
                this.multiChoiceField = value;
            }
        }
        
        /// <remarks/>
        public TextBlankType textBlank {
            get {
                return this.textBlankField;
            }
            set {
                this.textBlankField = value;
            }
        }
        
        /// <remarks/>
        public TextAreaType textArea {
            get {
                return this.textAreaField;
            }
            set {
                this.textAreaField = value;
            }
        }
        
        /// <remarks/>
        public TextOnlyType textOnly {
            get {
                return this.textOnlyField;
            }
            set {
                this.textOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suffixMessage")]
        public string[] suffixMessage {
            get {
                return this.suffixMessageField;
            }
            set {
                this.suffixMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public conditionsConditionPresent present {
            get {
                return this.presentField;
            }
            set {
                this.presentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public conditionsConditionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public conditionsConditionUsed used {
            get {
                return this.usedField;
            }
            set {
                this.usedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public conditionsConditionChanged changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class SingleChoiceType {
        
        private ItemType[] itemField;
        
        private object[] messageSegmentField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public ItemType[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageSegment")]
        public object[] messageSegment {
            get {
                return this.messageSegmentField;
            }
            set {
                this.messageSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class ItemType {
        
        private string nameField;
        
        private string itemValueField;
        
        private ItemTypeChecked checkedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string itemValue {
            get {
                return this.itemValueField;
            }
            set {
                this.itemValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ItemTypeChecked @checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum ItemTypeChecked {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdReplyDataType {
        
        private string statusField;
        
        private RejectType rejectField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public RejectType reject {
            get {
                return this.rejectField;
            }
            set {
                this.rejectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class RejectType {
        
        private string codeField;
        
        private string descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdReplyInfoType {
        
        private string typeField;
        
        private string appNoField;
        
        private string lcNoField;
        
        private string amendNoField;
        
        private string cancNoField;
        
        private string advNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lcNo {
            get {
                return this.lcNoField;
            }
            set {
                this.lcNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string amendNo {
            get {
                return this.amendNoField;
            }
            set {
                this.amendNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cancNo {
            get {
                return this.cancNoField;
            }
            set {
                this.cancNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string advNo {
            get {
                return this.advNoField;
            }
            set {
                this.advNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdCancInfoType {
        
        private string appNoField;
        
        private string cancNoField;
        
        private string cancDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cancNo {
            get {
                return this.cancNoField;
            }
            set {
                this.cancNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cancDate {
            get {
                return this.cancDateField;
            }
            set {
                this.cancDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdCancDataType {
        
        private AmountType availableAmountField;
        
        private CurrencyType currencyField;
        
        private string promiserField;
        
        private string undertakerField;
        
        /// <remarks/>
        public AmountType availableAmount {
            get {
                return this.availableAmountField;
            }
            set {
                this.availableAmountField = value;
            }
        }
        
        /// <remarks/>
        public CurrencyType currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string promiser {
            get {
                return this.promiserField;
            }
            set {
                this.promiserField = value;
            }
        }
        
        /// <remarks/>
        public string undertaker {
            get {
                return this.undertakerField;
            }
            set {
                this.undertakerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class AmountType {
        
        private string valueField;
        
        private string chineseField;
        
        private AmountTypeChanged changedField;
        
        private bool changedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chinese {
            get {
                return this.chineseField;
            }
            set {
                this.chineseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AmountTypeChanged changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum AmountTypeChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class CurrencyType {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdAdvInfoType {
        
        private string appNoField;
        
        private string amendNoField;
        
        private string amendCountField;
        
        private string advNoField;
        
        private string advDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string amendNo {
            get {
                return this.amendNoField;
            }
            set {
                this.amendNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string amendCount {
            get {
                return this.amendCountField;
            }
            set {
                this.amendCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string advNo {
            get {
                return this.advNoField;
            }
            set {
                this.advNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string advDate {
            get {
                return this.advDateField;
            }
            set {
                this.advDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdAmendItemType {
        
        private string itemNameField;
        
        private string oldValueField;
        
        private string newValueField;
        
        /// <remarks/>
        public string itemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public string oldValue {
            get {
                return this.oldValueField;
            }
            set {
                this.oldValueField = value;
            }
        }
        
        /// <remarks/>
        public string newValue {
            get {
                return this.newValueField;
            }
            set {
                this.newValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdAmendInfoType {
        
        private string appNoField;
        
        private string amendNoField;
        
        private string amendCountField;
        
        private string amendDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string amendNo {
            get {
                return this.amendNoField;
            }
            set {
                this.amendNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string amendCount {
            get {
                return this.amendCountField;
            }
            set {
                this.amendCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string amendDate {
            get {
                return this.amendDateField;
            }
            set {
                this.amendDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdAppInfoType {
        
        private string lcaTitleField;
        
        private string lcaHeaderField;
        
        private conditionsCondition[] conditionsField;
        
        private string lcaTailField;
        
        private string appNoField;
        
        private string appDateField;
        
        /// <remarks/>
        public string lcaTitle {
            get {
                return this.lcaTitleField;
            }
            set {
                this.lcaTitleField = value;
            }
        }
        
        /// <remarks/>
        public string lcaHeader {
            get {
                return this.lcaHeaderField;
            }
            set {
                this.lcaHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("condition", IsNullable=false)]
        public conditionsCondition[] conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        public string lcaTail {
            get {
                return this.lcaTailField;
            }
            set {
                this.lcaTailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appDate {
            get {
                return this.appDateField;
            }
            set {
                this.appDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdInfoType {
        
        private string appNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appNo {
            get {
                return this.appNoField;
            }
            set {
                this.appNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdDataType {
        
        private LcdDataTypePayment paymentField;
        
        private LcdDataTypeIsPartialShipment isPartialShipmentField;
        
        private LcdDataTypeIsCSCConditions isCSCConditionsField;
        
        private string cSCSalesDeptField;
        
        /// <remarks/>
        public LcdDataTypePayment payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public LcdDataTypeIsPartialShipment isPartialShipment {
            get {
                return this.isPartialShipmentField;
            }
            set {
                this.isPartialShipmentField = value;
            }
        }
        
        /// <remarks/>
        public LcdDataTypeIsCSCConditions isCSCConditions {
            get {
                return this.isCSCConditionsField;
            }
            set {
                this.isCSCConditionsField = value;
            }
        }
        
        /// <remarks/>
        public string CSCSalesDept {
            get {
                return this.cSCSalesDeptField;
            }
            set {
                this.cSCSalesDeptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdDataTypePayment {
        
        private LcdDataTypePaymentTerm termField;
        
        private string daysField;
        
        private string dateField;
        
        /// <remarks/>
        public LcdDataTypePaymentTerm term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public string days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum LcdDataTypePaymentTerm {
        
        /// <remarks/>
        atSight,
        
        /// <remarks/>
        atDaysAfterSight,
        
        /// <remarks/>
        atDaysAfterDate,
        
        /// <remarks/>
        onDate,
        
        /// <remarks/>
        atDaysAfterBLDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum LcdDataTypeIsPartialShipment {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum LcdDataTypeIsCSCConditions {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdType {
        
        private string lcTitleField;
        
        private LcdTypeLcType lcTypeField;
        
        private string lcHeaderField;
        
        private string lcNoField;
        
        private string issuingDateField;
        
        private BankType issuingBankField;
        
        private BankType advisingBankField;
        
        private string advisingDateField;
        
        private string advisingBankNoField;
        
        private BankType payingBankField;
        
        private CompanyType applicantField;
        
        private CompanyType beneficiaryField;
        
        private AmountType amountField;
        
        private CurrencyType currencyField;
        
        private LcdTypeExpiryDate expiryDateField;
        
        private string[] lcConditionsField;
        
        private string[] lcAdditionalConditionsField;
        
        private conditionsCondition[] conditionsField;
        
        private string lcTailField;
        
        private string advisingBankNotesField;
        
        /// <remarks/>
        public string lcTitle {
            get {
                return this.lcTitleField;
            }
            set {
                this.lcTitleField = value;
            }
        }
        
        /// <remarks/>
        public LcdTypeLcType lcType {
            get {
                return this.lcTypeField;
            }
            set {
                this.lcTypeField = value;
            }
        }
        
        /// <remarks/>
        public string lcHeader {
            get {
                return this.lcHeaderField;
            }
            set {
                this.lcHeaderField = value;
            }
        }
        
        /// <remarks/>
        public string lcNo {
            get {
                return this.lcNoField;
            }
            set {
                this.lcNoField = value;
            }
        }
        
        /// <remarks/>
        public string issuingDate {
            get {
                return this.issuingDateField;
            }
            set {
                this.issuingDateField = value;
            }
        }
        
        /// <remarks/>
        public BankType issuingBank {
            get {
                return this.issuingBankField;
            }
            set {
                this.issuingBankField = value;
            }
        }
        
        /// <remarks/>
        public BankType advisingBank {
            get {
                return this.advisingBankField;
            }
            set {
                this.advisingBankField = value;
            }
        }
        
        /// <remarks/>
        public string advisingDate {
            get {
                return this.advisingDateField;
            }
            set {
                this.advisingDateField = value;
            }
        }
        
        /// <remarks/>
        public string advisingBankNo {
            get {
                return this.advisingBankNoField;
            }
            set {
                this.advisingBankNoField = value;
            }
        }
        
        /// <remarks/>
        public BankType payingBank {
            get {
                return this.payingBankField;
            }
            set {
                this.payingBankField = value;
            }
        }
        
        /// <remarks/>
        public CompanyType applicant {
            get {
                return this.applicantField;
            }
            set {
                this.applicantField = value;
            }
        }
        
        /// <remarks/>
        public CompanyType beneficiary {
            get {
                return this.beneficiaryField;
            }
            set {
                this.beneficiaryField = value;
            }
        }
        
        /// <remarks/>
        public AmountType amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public CurrencyType currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public LcdTypeExpiryDate expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("lcCond", IsNullable=false)]
        public string[] lcConditions {
            get {
                return this.lcConditionsField;
            }
            set {
                this.lcConditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("lcAddCond", IsNullable=false)]
        public string[] lcAdditionalConditions {
            get {
                return this.lcAdditionalConditionsField;
            }
            set {
                this.lcAdditionalConditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("condition", IsNullable=false)]
        public conditionsCondition[] conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        public string lcTail {
            get {
                return this.lcTailField;
            }
            set {
                this.lcTailField = value;
            }
        }
        
        /// <remarks/>
        public string advisingBankNotes {
            get {
                return this.advisingBankNotesField;
            }
            set {
                this.advisingBankNotesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum LcdTypeLcType {
        
        /// <remarks/>
        sight,
        
        /// <remarks/>
        usance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class BankType {
        
        private string nameField;
        
        private string codeField;
        
        private string branchNameField;
        
        private string branchCodeField;
        
        private string addressField;
        
        private string phoneField;
        
        private BankTypeChanged changedField;
        
        private bool changedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string branchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BankTypeChanged changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum BankTypeChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class CompanyType {
        
        private string nameField;
        
        private CompanyTypeNameChanged nameChangedField;
        
        private bool nameChangedFieldSpecified;
        
        private string regNoField;
        
        private string addressField;
        
        private CompanyTypeAddressChanged addressChangedField;
        
        private bool addressChangedFieldSpecified;
        
        private string phoneField;
        
        private CompanyTypePhoneChanged phoneChangedField;
        
        private bool phoneChangedFieldSpecified;
        
        private string chiefNameField;
        
        private CompanyTypeChiefNameChanged chiefNameChangedField;
        
        private bool chiefNameChangedFieldSpecified;
        
        private string chiefTitleField;
        
        private CompanyTypeChiefTitleChanged chiefTitleChangedField;
        
        private bool chiefTitleChangedFieldSpecified;
        
        private string chiefEmailField;
        
        private CompanyTypeChiefEmailChanged chiefEmailChangedField;
        
        private bool chiefEmailChangedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyTypeNameChanged nameChanged {
            get {
                return this.nameChangedField;
            }
            set {
                this.nameChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nameChangedSpecified {
            get {
                return this.nameChangedFieldSpecified;
            }
            set {
                this.nameChangedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string regNo {
            get {
                return this.regNoField;
            }
            set {
                this.regNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyTypeAddressChanged addressChanged {
            get {
                return this.addressChangedField;
            }
            set {
                this.addressChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addressChangedSpecified {
            get {
                return this.addressChangedFieldSpecified;
            }
            set {
                this.addressChangedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyTypePhoneChanged phoneChanged {
            get {
                return this.phoneChangedField;
            }
            set {
                this.phoneChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool phoneChangedSpecified {
            get {
                return this.phoneChangedFieldSpecified;
            }
            set {
                this.phoneChangedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chiefName {
            get {
                return this.chiefNameField;
            }
            set {
                this.chiefNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyTypeChiefNameChanged chiefNameChanged {
            get {
                return this.chiefNameChangedField;
            }
            set {
                this.chiefNameChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chiefNameChangedSpecified {
            get {
                return this.chiefNameChangedFieldSpecified;
            }
            set {
                this.chiefNameChangedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chiefTitle {
            get {
                return this.chiefTitleField;
            }
            set {
                this.chiefTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyTypeChiefTitleChanged chiefTitleChanged {
            get {
                return this.chiefTitleChangedField;
            }
            set {
                this.chiefTitleChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chiefTitleChangedSpecified {
            get {
                return this.chiefTitleChangedFieldSpecified;
            }
            set {
                this.chiefTitleChangedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string chiefEmail {
            get {
                return this.chiefEmailField;
            }
            set {
                this.chiefEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompanyTypeChiefEmailChanged chiefEmailChanged {
            get {
                return this.chiefEmailChangedField;
            }
            set {
                this.chiefEmailChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chiefEmailChangedSpecified {
            get {
                return this.chiefEmailChangedFieldSpecified;
            }
            set {
                this.chiefEmailChangedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum CompanyTypeNameChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum CompanyTypeAddressChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum CompanyTypePhoneChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum CompanyTypeChiefNameChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum CompanyTypeChiefTitleChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum CompanyTypeChiefEmailChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class LcdTypeExpiryDate {
        
        private LcdTypeExpiryDateChanged changedField;
        
        private bool changedFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LcdTypeExpiryDateChanged changed {
            get {
                return this.changedField;
            }
            set {
                this.changedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified {
            get {
                return this.changedFieldSpecified;
            }
            set {
                this.changedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum LcdTypeExpiryDateChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class CPType {
        
        private string cpNoField;
        
        private string issuingDateField;
        
        private string dueDateField;
        
        private BankType issuingBankField;
        
        private string cpAccountField;
        
        private BankType payingBankField;
        
        private CompanyType payerField;
        
        private string payerUndertakerField;
        
        private CompanyType beneficiaryField;
        
        private AmountType amountField;
        
        private CurrencyType currencyField;
        
        private string signetField;
        
        /// <remarks/>
        public string cpNo {
            get {
                return this.cpNoField;
            }
            set {
                this.cpNoField = value;
            }
        }
        
        /// <remarks/>
        public string issuingDate {
            get {
                return this.issuingDateField;
            }
            set {
                this.issuingDateField = value;
            }
        }
        
        /// <remarks/>
        public string dueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        public BankType issuingBank {
            get {
                return this.issuingBankField;
            }
            set {
                this.issuingBankField = value;
            }
        }
        
        /// <remarks/>
        public string cpAccount {
            get {
                return this.cpAccountField;
            }
            set {
                this.cpAccountField = value;
            }
        }
        
        /// <remarks/>
        public BankType payingBank {
            get {
                return this.payingBankField;
            }
            set {
                this.payingBankField = value;
            }
        }
        
        /// <remarks/>
        public CompanyType payer {
            get {
                return this.payerField;
            }
            set {
                this.payerField = value;
            }
        }
        
        /// <remarks/>
        public string payerUndertaker {
            get {
                return this.payerUndertakerField;
            }
            set {
                this.payerUndertakerField = value;
            }
        }
        
        /// <remarks/>
        public CompanyType beneficiary {
            get {
                return this.beneficiaryField;
            }
            set {
                this.beneficiaryField = value;
            }
        }
        
        /// <remarks/>
        public AmountType amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public CurrencyType currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string signet {
            get {
                return this.signetField;
            }
            set {
                this.signetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class TextOnlyType {
        
        private string[] messageSegmentField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageSegment")]
        public string[] messageSegment {
            get {
                return this.messageSegmentField;
            }
            set {
                this.messageSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class TextAreaType {
        
        private TextAreaTypeArea[] areaField;
        
        private object[] messageSegmentField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("area")]
        public TextAreaTypeArea[] area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageSegment")]
        public object[] messageSegment {
            get {
                return this.messageSegmentField;
            }
            set {
                this.messageSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class TextAreaTypeArea {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class TextBlankType {
        
        private TextBlankTypeBlank[] blankField;
        
        private string[] messageSegmentField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("blank")]
        public TextBlankTypeBlank[] blank {
            get {
                return this.blankField;
            }
            set {
                this.blankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageSegment")]
        public string[] messageSegment {
            get {
                return this.messageSegmentField;
            }
            set {
                this.messageSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class TextBlankTypeBlank {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.uxcds.com/xmlschema/cds")]
    public partial class MultiChoiceType {
        
        private ItemType[] itemField;
        
        private object[] messageSegmentField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public ItemType[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageSegment")]
        public object[] messageSegment {
            get {
                return this.messageSegmentField;
            }
            set {
                this.messageSegmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum conditionsConditionPresent {
        
        /// <remarks/>
        sight,
        
        /// <remarks/>
        usance,
        
        /// <remarks/>
        specify,
        
        /// <remarks/>
        cross,
        
        /// <remarks/>
        general,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum conditionsConditionType {
        
        /// <remarks/>
        singleChoice,
        
        /// <remarks/>
        multiChoice,
        
        /// <remarks/>
        textBlank,
        
        /// <remarks/>
        textArea,
        
        /// <remarks/>
        textOnly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum conditionsConditionUsed {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    public enum conditionsConditionChanged {
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        @false,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.uxcds.com/xmlschema/cds", IsNullable=false)]
    public partial class conditions {
        
        private conditionsCondition[] conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition")]
        public conditionsCondition[] condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.uxcds.com/xmlschema/cds")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.uxcds.com/xmlschema/cds", IsNullable=false)]
    public partial class CDSLcdApplication {
        
        private LcdAppInfoType lcAppInfoField;
        
        private LcdType lcDocField;
        
        private CPType cpDocField;
        
        private LcdDataType lcDataField;
        
        private string versionField;
        
        /// <remarks/>
        public LcdAppInfoType lcAppInfo {
            get {
                return this.lcAppInfoField;
            }
            set {
                this.lcAppInfoField = value;
            }
        }
        
        /// <remarks/>
        public LcdType lcDoc {
            get {
                return this.lcDocField;
            }
            set {
                this.lcDocField = value;
            }
        }
        
        /// <remarks/>
        public CPType cpDoc {
            get {
                return this.cpDocField;
            }
            set {
                this.cpDocField = value;
            }
        }
        
        /// <remarks/>
        public LcdDataType lcData {
            get {
                return this.lcDataField;
            }
            set {
                this.lcDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
}
