//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EBank {
    
    private EBankLoanrecord loanrecordField;
    
    /// <remarks/>
    public EBankLoanrecord loanrecord {
        get {
            return this.loanrecordField;
        }
        set {
            this.loanrecordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EBankLoanrecord {
    
    private string draftNoField;
    
    private string confirmdateField;
    
    private string coidField;
    
    private string issuebankidField;
    
    private string lcanoField;
    
    /// <remarks/>
    public string draftNo {
        get {
            return this.draftNoField;
        }
        set {
            this.draftNoField = value;
        }
    }
    
    /// <remarks/>
    public string confirmdate {
        get {
            return this.confirmdateField;
        }
        set {
            this.confirmdateField = value;
        }
    }
    
    /// <remarks/>
    public string coid {
        get {
            return this.coidField;
        }
        set {
            this.coidField = value;
        }
    }
    
    /// <remarks/>
    public string issuebankid {
        get {
            return this.issuebankidField;
        }
        set {
            this.issuebankidField = value;
        }
    }
    
    /// <remarks/>
    public string lcano {
        get {
            return this.lcanoField;
        }
        set {
            this.lcanoField = value;
        }
    }
}
