//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class EnegoApply {
    
    private string lcNoField;
    
    private string issuingDateField;
    
    private int invoiceCountField;
    
    private decimal amountField;
    
    private string applyDateField;
    
    private EnegoApplyPrice priceField;
    
    private int productListField;
    
    private string expiryDateField;
    
    private string applicantIdField;
    
    private string applicantNameField;
    
    private string applicantAddrField;
    
    private string beneficiaryNameField;
    
    private string beneficiaryIdField;
    
    private string beneficiaryAddrField;
    
    private string issuingBankNameField;
    
    private string issuingBranchNameField;
    
    private decimal availableAmtField;
    
    private string incomeAccountField;
    
    private string outcomeAccountField;
    
    private string deliveryDateField;
    
    private string enegoInvoiceDateField;
    
    private string enegoExpiryDateField;
    
    private string enegoNoField;
    
    private string digitalNoField;
    
    private string uploadFileNameOriginField;
    
    private string uploadFileNameField;
    
    private string advisingBankIdField;
    
    private string issuingBankIdField;
    
    private string advisingBranchIdField;
    
    private string issuingBranchIdField;
    
    private string invoiceFileField;
    
    private string invoiceDateField;
    
    private string payDayTypeField;
    
    private string afterDayField;
    
    /// <remarks/>
    public string lcNo {
        get {
            return this.lcNoField;
        }
        set {
            this.lcNoField = value;
        }
    }
    
    /// <remarks/>
    public string issuingDate {
        get {
            return this.issuingDateField;
        }
        set {
            this.issuingDateField = value;
        }
    }
    
    /// <remarks/>
    public int invoiceCount {
        get {
            return this.invoiceCountField;
        }
        set {
            this.invoiceCountField = value;
        }
    }
    
    /// <remarks/>
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public string applyDate {
        get {
            return this.applyDateField;
        }
        set {
            this.applyDateField = value;
        }
    }
    
    /// <remarks/>
    public EnegoApplyPrice price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public int productList {
        get {
            return this.productListField;
        }
        set {
            this.productListField = value;
        }
    }
    
    /// <remarks/>
    public string expiryDate {
        get {
            return this.expiryDateField;
        }
        set {
            this.expiryDateField = value;
        }
    }
    
    /// <remarks/>
    public string applicantId {
        get {
            return this.applicantIdField;
        }
        set {
            this.applicantIdField = value;
        }
    }
    
    /// <remarks/>
    public string applicantName {
        get {
            return this.applicantNameField;
        }
        set {
            this.applicantNameField = value;
        }
    }
    
    /// <remarks/>
    public string applicantAddr {
        get {
            return this.applicantAddrField;
        }
        set {
            this.applicantAddrField = value;
        }
    }
    
    /// <remarks/>
    public string beneficiaryName {
        get {
            return this.beneficiaryNameField;
        }
        set {
            this.beneficiaryNameField = value;
        }
    }
    
    /// <remarks/>
    public string beneficiaryId {
        get {
            return this.beneficiaryIdField;
        }
        set {
            this.beneficiaryIdField = value;
        }
    }
    
    /// <remarks/>
    public string beneficiaryAddr {
        get {
            return this.beneficiaryAddrField;
        }
        set {
            this.beneficiaryAddrField = value;
        }
    }
    
    /// <remarks/>
    public string issuingBankName {
        get {
            return this.issuingBankNameField;
        }
        set {
            this.issuingBankNameField = value;
        }
    }
    
    /// <remarks/>
    public string issuingBranchName {
        get {
            return this.issuingBranchNameField;
        }
        set {
            this.issuingBranchNameField = value;
        }
    }
    
    /// <remarks/>
    public decimal availableAmt {
        get {
            return this.availableAmtField;
        }
        set {
            this.availableAmtField = value;
        }
    }
    
    /// <remarks/>
    public string incomeAccount {
        get {
            return this.incomeAccountField;
        }
        set {
            this.incomeAccountField = value;
        }
    }
    
    /// <remarks/>
    public string outcomeAccount {
        get {
            return this.outcomeAccountField;
        }
        set {
            this.outcomeAccountField = value;
        }
    }
    
    /// <remarks/>
    public string deliveryDate {
        get {
            return this.deliveryDateField;
        }
        set {
            this.deliveryDateField = value;
        }
    }
    
    /// <remarks/>
    public string enegoInvoiceDate {
        get {
            return this.enegoInvoiceDateField;
        }
        set {
            this.enegoInvoiceDateField = value;
        }
    }
    
    /// <remarks/>
    public string enegoExpiryDate {
        get {
            return this.enegoExpiryDateField;
        }
        set {
            this.enegoExpiryDateField = value;
        }
    }
    
    /// <remarks/>
    public string enegoNo {
        get {
            return this.enegoNoField;
        }
        set {
            this.enegoNoField = value;
        }
    }
    
    /// <remarks/>
    public string digitalNo {
        get {
            return this.digitalNoField;
        }
        set {
            this.digitalNoField = value;
        }
    }
    
    /// <remarks/>
    public string uploadFileNameOrigin {
        get {
            return this.uploadFileNameOriginField;
        }
        set {
            this.uploadFileNameOriginField = value;
        }
    }
    
    /// <remarks/>
    public string uploadFileName {
        get {
            return this.uploadFileNameField;
        }
        set {
            this.uploadFileNameField = value;
        }
    }
    
    /// <remarks/>
    public string advisingBankId {
        get {
            return this.advisingBankIdField;
        }
        set {
            this.advisingBankIdField = value;
        }
    }
    
    /// <remarks/>
    public string issuingBankId {
        get {
            return this.issuingBankIdField;
        }
        set {
            this.issuingBankIdField = value;
        }
    }
    
    /// <remarks/>
    public string advisingBranchId {
        get {
            return this.advisingBranchIdField;
        }
        set {
            this.advisingBranchIdField = value;
        }
    }
    
    /// <remarks/>
    public string issuingBranchId {
        get {
            return this.issuingBranchIdField;
        }
        set {
            this.issuingBranchIdField = value;
        }
    }
    
    /// <remarks/>
    public string invoiceFile {
        get {
            return this.invoiceFileField;
        }
        set {
            this.invoiceFileField = value;
        }
    }
    
    /// <remarks/>
    public string invoiceDate {
        get {
            return this.invoiceDateField;
        }
        set {
            this.invoiceDateField = value;
        }
    }
    
    /// <remarks/>
    public string payDayType {
        get {
            return this.payDayTypeField;
        }
        set {
            this.payDayTypeField = value;
        }
    }
    
    /// <remarks/>
    public string afterDay {
        get {
            return this.afterDayField;
        }
        set {
            this.afterDayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EnegoApplyPrice {
    
    private decimal priceField;
    
    private string priceChineseField;
    
    /// <remarks/>
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public string priceChinese {
        get {
            return this.priceChineseField;
        }
        set {
            this.priceChineseField = value;
        }
    }
}
