//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.8.4084.0 自動產生。
// 
namespace ModelCore.Schema.UXCDS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cdslc.uxcds.com/CDSLC#draft", IsNullable=false)]
    public partial class invoiceItem {
        
        /// <remarks/>
        public string invoiceDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtInvoiceDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtInvoiceDateSpecified;
        
        /// <remarks/>
        public invoiceItemBuyer buyer;
        
        /// <remarks/>
        public string taxNo;
        
        /// <remarks/>
        public string dispatchmentAdviceNo;
        
        /// <remarks/>
        public string checkNo;
        
        /// <remarks/>
        public string orderNo;
        
        /// <remarks/>
        public string ladingNo;
        
        /// <remarks/>
        public string lcNo;
        
        /// <remarks/>
        public decimal piece;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pieceSpecified;
        
        /// <remarks/>
        public decimal weight;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified;
        
        /// <remarks/>
        public decimal freightAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool freightAmountSpecified;
        
        /// <remarks/>
        public decimal costAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costAmountSpecified;
        
        /// <remarks/>
        public decimal freightCostAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool freightCostAmountSpecified;
        
        /// <remarks/>
        public string dutiable;
        
        /// <remarks/>
        public string zeroTaxRate;
        
        /// <remarks/>
        public string dutyFree;
        
        /// <remarks/>
        public decimal salesTax;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salesTaxSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> grandAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grandAmountSpecified;
        
        /// <remarks/>
        public string chineseGrandAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> discount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountSpecified;
        
        /// <remarks/>
        public decimal adjustment;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adjustmentSpecified;
        
        /// <remarks/>
        public decimal appendantPay;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool appendantPaySpecified;
        
        /// <remarks/>
        public decimal appendantSubtotalPreTax;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool appendantSubtotalPreTaxSpecified;
        
        /// <remarks/>
        public decimal calcSubtotal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool calcSubtotalSpecified;
        
        /// <remarks/>
        public decimal calcDiscount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool calcDiscountSpecified;
        
        /// <remarks/>
        public string remark;
        
        /// <remarks/>
        public string undertaker;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("product", IsNullable=false)]
        public invoiceItemProduct[] details;
        
        /// <remarks/>
        public string invoiceSeal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> uploadStatus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uploadStatusSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> interestRate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool interestRateSpecified;
        
        /// <remarks/>
        public string goodsRemark;
        
        /// <remarks/>
        public string orderItemNo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string No;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string draftNo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string poNo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class invoiceItemBuyer {
        
        /// <remarks/>
        public string postCode;
        
        /// <remarks/>
        public string address;
        
        /// <remarks/>
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string receiptNo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class invoiceItemProduct {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item")]
        public invoiceItemProductItem[] item;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string brief;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class invoiceItemProductItem {
        
        /// <remarks/>
        public string spec;
        
        /// <remarks/>
        public invoiceItemProductItemPiece piece;
        
        /// <remarks/>
        public invoiceItemProductItemWeight weight;
        
        /// <remarks/>
        public decimal unitFreight;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitFreightSpecified;
        
        /// <remarks/>
        public decimal unitCost;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitCostSpecified;
        
        /// <remarks/>
        public decimal freightAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool freightAmountSpecified;
        
        /// <remarks/>
        public decimal costAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costAmountSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> originalPrice;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalPriceSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string No;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class invoiceItemProductItemPiece {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class invoiceItemProductItemWeight {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cdslc.uxcds.com/CDSLC#draft", IsNullable=false)]
    public partial class invoices {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoiceItem")]
        public invoiceItem[] invoiceItem;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cdslc.uxcds.com/CDSLC#draft", IsNullable=false)]
    public partial class CDSLC {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("draft")]
        public CDSLCDraft[] draft;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class CDSLCDraft {
        
        /// <remarks/>
        public string lcNo;
        
        /// <remarks/>
        public string shipmentDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtShipmentDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtShipmentDateSpecified;
        
        /// <remarks/>
        public string negoDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dtNegoDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtNegoDateSpecified;
        
        /// <remarks/>
        public decimal amount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified;
        
        /// <remarks/>
        public string amountInChinese;
        
        /// <remarks/>
        public string applicantName;
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int usance;
        
        /// <remarks/>
        public CDSLCDraftCustomer Customer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("goods")]
        public CDSLCDraftGoods[] goods;
        
        /// <remarks/>
        public string remark;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> uploadStatus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool uploadStatusSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DueDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueDateSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("invoiceItem", IsNullable=false)]
        public invoiceItem[] invoices;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string No;
        
        public CDSLCDraft() {
            this.usance = 0;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class CDSLCDraftCustomer {
        
        /// <remarks/>
        public string orgSeqNo;
        
        /// <remarks/>
        public string batchNo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class CDSLCDraftGoods {
        
        /// <remarks/>
        public string itemName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> subTotal;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subTotalSpecified;
        
        /// <remarks/>
        public string applicantAddr;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cdslc.uxcds.com/CDSLC#draft", IsNullable=false)]
    public partial class ARCredit {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creditItem")]
        public ARCreditCreditItem[] creditItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("orderItem")]
        public ARCreditOrderItem[] orderItem;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("POPayoff")]
        public ARCreditPOPayoff[] POPayoff;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class ARCreditCreditItem {
        
        /// <remarks/>
        public string agreementNo;
        
        /// <remarks/>
        public string bankCode;
        
        /// <remarks/>
        public string validationDate;
        
        /// <remarks/>
        public string expirationDate;
        
        /// <remarks/>
        public int creditDays;
        
        /// <remarks/>
        public string buyerReceiptNo;
        
        /// <remarks/>
        public string sellerReceiptNo;
        
        /// <remarks/>
        public decimal creditAmount;
        
        /// <remarks/>
        public ARCreditCreditItemCustomer Customer;
        
        /// <remarks/>
        public string uploadStatus;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class ARCreditCreditItemCustomer {
        
        /// <remarks/>
        public string orgSeqNo;
        
        /// <remarks/>
        public string batchNo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class ARCreditOrderItem {
        
        /// <remarks/>
        public decimal purchaseAmount;
        
        /// <remarks/>
        public string purchaseDate;
        
        /// <remarks/>
        public int discountDays;
        
        /// <remarks/>
        public string expirationDate;
        
        /// <remarks/>
        public decimal managementFee;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool managementFeeSpecified;
        
        /// <remarks/>
        public decimal agentFee;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool agentFeeSpecified;
        
        /// <remarks/>
        public decimal appropriateAmount;
        
        /// <remarks/>
        public decimal managementFeeNoTax;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool managementFeeNoTaxSpecified;
        
        /// <remarks/>
        public decimal agentFeeNoTax;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool agentFeeNoTaxSpecified;
        
        /// <remarks/>
        public decimal taxAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxAmountSpecified;
        
        /// <remarks/>
        public string contractQuarter;
        
        /// <remarks/>
        public string contractNo;
        
        /// <remarks/>
        public string agreementNo;
        
        /// <remarks/>
        public ARCreditOrderItemCustomer Customer;
        
        /// <remarks/>
        public string uploadStatus;
        
        /// <remarks/>
        public string bankCode;
        
        /// <remarks/>
        public string buyerReceiptNo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("invoiceItem", IsNullable=false)]
        public invoiceItem[] invoices;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string No;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class ARCreditOrderItemCustomer {
        
        /// <remarks/>
        public string orgSeqNo;
        
        /// <remarks/>
        public string batchNo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class ARCreditPOPayoff {
        
        /// <remarks/>
        public string PayoffDate;
        
        /// <remarks/>
        public ARCreditPOPayoffCustomer Customer;
        
        /// <remarks/>
        public string PurchaseNo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PayoffAmount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayoffAmountSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://cdslc.uxcds.com/CDSLC#draft")]
    public partial class ARCreditPOPayoffCustomer {
        
        /// <remarks/>
        public string orgSeqNo;
        
        /// <remarks/>
        public string batchNo;
    }
}
